[project]
name = "aero-proto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.11",
    "pandas>=3.0.1",
    "pyzmq>=27.1.0",
]
